const assert=require('node:assert/strict');
const M=require('../app/src/main/assets/model.js');
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
test('month boundary recurrence',()=>assert.equal(M.nextDate('2026-09-30','daily'),'2026-10-01'));
test('weekdays skip weekend',()=>assert.equal(M.nextDate('2026-09-25','weekdays'),'2026-09-28'));
test('alternate days cross year boundary',()=>assert.equal(M.nextDate('2026-12-31','alternate'),'2027-01-02'));
test('weekly event occurrence',()=>{assert(M.occurs({date:'2026-09-01',repeat:'weekly'},'2026-09-29'));assert(!M.occurs({date:'2026-09-01',repeat:'weekly'},'2026-09-30'));});
test('no occurrence before event starts',()=>assert(!M.occurs({date:'2026-10-01',repeat:'daily'},'2026-09-30')));
test('non-repeating event only on its date',()=>{assert(M.occurs({date:'2026-09-27',repeat:'none'},'2026-09-27'));assert(!M.occurs({date:'2026-09-27',repeat:'none'},'2026-09-28'));});
test('completion produces one next occurrence',()=>{const d=M.defaults();d.tasks.push({id:'t',title:'Test',date:'2026-09-26',repeat:'daily',done:false,subtasks:[{title:'Step',done:true}]});const now=new Date('2026-09-27T15:00:00').getTime();M.completeTask(d,'t',now);assert.equal(d.tasks.length,2);assert.equal(d.tasks[1].date,'2026-09-27');assert.equal(d.tasks[1].subtasks[0].done,false);M.completeTask(d,'t',now);M.completeTask(d,'t',now);assert.equal(d.tasks.length,2);});
test('work totals use milliseconds',()=>assert.equal(M.totalMinutes([{durationMs:90000},{durationMs:30000}]),2));
test('invalid backup rejected',()=>{assert(!M.validData({}));assert(M.validData(M.defaults()));});
test('DST date addition stays on local date',()=>assert.equal(M.nextDate('2026-10-24','daily'),'2026-10-25'));
test('malformed imported task rejected',()=>{const d=M.defaults();d.tasks=[{id:'broken'}];assert(!M.validData(d));});
test('malformed settings rejected',()=>{const d=M.defaults();d.settings.blocked=null;assert(!M.validData(d));});
test('backup rejects nonnumeric history',()=>{const d={...M.defaults(),history:[{durationMs:'not a number'}]};assert(!M.validBackup(d));assert(M.validBackup({...M.defaults(),history:[]}));});
test('AMOLED and rotation enabled for new installs',()=>{const s=M.defaults().settings;assert.equal(s.dark,true);assert.equal(s.standbyAuto,true);});
test('version 1.0 backups remain valid without StandBy settings',()=>{const d=M.defaults();delete d.settings.standbyAuto;delete d.settings.standbyNight;delete d.settings.standbyDim;d.settings.dark=false;assert(M.validBackup({...d,history:[]}));assert.equal({...M.defaults().settings,...d.settings}.dark,false);});
test('invalid StandBy preferences rejected',()=>{const d=M.defaults();d.settings.standbyAuto='yes';assert(!M.validData(d));});
test('StandBy enters only on the timer screen during a running landscape session',()=>{assert(M.shouldStandby({status:'running',landscape:true}));assert(!M.shouldStandby({status:'running',landscape:false}));assert(!M.shouldStandby({status:'idle',landscape:true}));assert(!M.shouldStandby({status:'running',landscape:true,page:'tasks'}));assert(!M.shouldStandby({status:'running',landscape:true,dialog:true}));});
test('manual StandBy supports portrait and paused sessions',()=>{assert(M.shouldStandby({status:'running',manual:true}));assert(M.shouldStandby({status:'paused',manual:true}));assert(!M.shouldStandby({status:'idle',manual:true}));});
test('automatic StandBy respects exit and rotation preference',()=>{assert(!M.shouldStandby({status:'running',landscape:true,dismissed:true}));assert(!M.shouldStandby({status:'running',landscape:true,auto:false}));assert(M.shouldStandby({status:'paused',landscape:true,active:true}));assert(!M.shouldStandby({status:'paused',landscape:true,active:false}));});
test('pixel shift stays small and changes once per minute',()=>{assert.deepEqual(M.standbyShift(0),M.standbyShift(59999));assert.notDeepEqual(M.standbyShift(59999),M.standbyShift(60000));for(let m=0;m<20;m++)assert(M.standbyShift(m*60000).every(n=>Math.abs(n)<=3));});
console.log(`${passed} model tests passed`);
